verison: 2

sources:
  - name: COVID19_EPIDEMIOLOGICAL_DATA
    database: COVID19_EPIDEMIOLOGICAL_DATA
    schema: public
    tables:
      - name: DEMOGRAPHICS
      
            
            
            
            
          
            
            
            
            
            
            
            