name: CI Pro

on:
  push:
    branches:
      - main

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    
 
  
  test-dbt:
    needs: lint-python
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dbt
      run: |
        pip install dbt
    
    - name: Run dbt tests
      run: |
        dbt test --profiles-dir .
    
  deploy:
    needs: test-dbt
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Production
      run: echo "Deploying to production"
