name: Sync Develop with Main

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  check_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch all branches
      run: git fetch --all

    - name: Check if the branch is ahead of upstream/main
      run: |
        UPSTREAM='origin/main'
        LOCAL=$(git rev-parse @)
        REMOTE=$(git rev-parse "$UPSTREAM")
        BASE=$(git merge-base @ "$UPSTREAM")

        if [ $LOCAL = $REMOTE ]; then
          echo "Your branch is up-to-date with main."
        elif [ $LOCAL = $BASE ]; then
          echo "Your branch is behind upstream/main. You should pull changes."
          exit 1
        elif [ $REMOTE = $BASE ]; then
          echo "Your branch is ahead of upstream/main."
        else:
          echo "Your branch has diverged from upstream/main."
          exit 1
        fi

    - name: Merge main into develop if behind
      if: failure() # Only merge if develop is behind main
      run: git merge origin/main
