name: Manual Merge Development to Main

on:
  workflow_dispatch:  # Este evento permite ejecutar la acción manualmente

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout development branch
        uses: actions/checkout@v2
        with:
          ref: develop  # Chequea el código de la rama development

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Fetch all branches
        run: |
          git fetch origin  # Trae todas las ramas del remoto
          git branch -r  # Verifica las ramas remotas disponibles

      - name: Merge development into main
        run: |
          git checkout main   # Cambia a la rama main
          git merge develop  # Hace merge de development a main
          git push origin main  # Hace push de los cambios a la rama main

      - name: Notify success
        run: echo "Merge from development to main completed successfully."
